export const GET_CATALOG_REQUEST = 'GET_CATALOG_REQUEST'
export const GET_CATALOG_SUCCESS = 'GET_CATALOG_SUCCESS'

export const OPEN_REPOSITORY = 'OPEN_REPOSITORY'

export const GET_TAGS_REQUEST = 'GET_TAGS_REQUEST'
export const GET_TAGS_SUCCESS = 'GET_TAGS_SUCCESS'
